[package]
name = "seminar-bayreuth-2022"
version = "0.1"
lean_version = "leanprover-community/lean:3.48.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "c9e2f05526bc6cc70578efcf0cda7d7fa261dab1"}
